USE MY_DB;

CREATE TABLE ENTRY (
  ENTRY_ID INTEGER NOT NULL AUTO_INCREMENT,
  ACCOUNT_ID INTEGER NOT NULL,
  RELEASE_DATE DATETIME NOT NULL,
  OPERATION_TYPE INTEGER NOT NULL,
  AMOUNT DECIMAL(10,2)NOT NULL,
  PRIMARY KEY(ENTRY_ID)
);