USE MY_DB;

CREATE TABLE ACCOUNT (
  ACCOUNT_ID INTEGER NOT NULL AUTO_INCREMENT,
  USER_ID INTEGER NOT NULL,
  AGENCY VARCHAR(200) NOT NULL,
  NUMBER_AGENCY VARCHAR(20) NOT NULL,
  PRIMARY KEY(ACCOUNT_ID)
);

